//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Default.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Default : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Default()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Default"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""65c030d8-d8db-4ce8-9f1f-2e3e03ce297e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""381027c0-ded5-43f9-9287-28eb3cc6a20f"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""8266a28d-f46c-453c-9ad4-9f562cf99098"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MeleeAtk"",
                    ""type"": ""Button"",
                    ""id"": ""3188d9ba-5360-45d9-8e67-1b28c2311cdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""0f8723be-88fc-4852-9326-4e948f342144"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""25fb39cd-e352-4883-8e58-bab274b1d4ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""236c5b8c-799b-4130-a7c2-54931a7c9d4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""5e4c5df1-46b4-4be0-b424-26c2dc14d303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventary"",
                    ""type"": ""Button"",
                    ""id"": ""dce9ae5e-d1a7-4fd7-b9db-1fad00c79f00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""ad52f977-9de0-4075-9d8f-2cf433390652"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StarFruit"",
                    ""type"": ""Button"",
                    ""id"": ""8bc73fde-5ad6-4b47-9626-077609515a17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""19185a6f-8c56-4911-9d61-421f6cac017e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar1"",
                    ""type"": ""Button"",
                    ""id"": ""1e883be8-0878-4fbb-814d-615ef44eb950"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar2"",
                    ""type"": ""Button"",
                    ""id"": ""483497da-f36a-4726-93e2-8978210f9f39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar3"",
                    ""type"": ""Button"",
                    ""id"": ""bc2a5529-2f22-4c0b-b152-da0963e89a60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar4"",
                    ""type"": ""Button"",
                    ""id"": ""8c40fa42-7d1c-42c8-bdf4-ded15a104460"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar5"",
                    ""type"": ""Button"",
                    ""id"": ""ebb95177-7b20-4e49-ad86-3835ef3e8e4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar6"",
                    ""type"": ""Button"",
                    ""id"": ""7ca3fcf4-eafb-4a00-9a8e-a32291c72cad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Value"",
                    ""id"": ""771ab99f-66c0-41eb-a391-b292d40bb637"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ExepEsc"",
                    ""type"": ""Button"",
                    ""id"": ""241c364e-5fd6-42d1-9e29-2d5afef2b9b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepTab"",
                    ""type"": ""Button"",
                    ""id"": ""568d4fa1-3914-4c28-99dc-fbb209c89e58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepLeftShift"",
                    ""type"": ""Button"",
                    ""id"": ""6a59d541-6e5a-465d-9cb0-7c08c107838e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepLeftAlt"",
                    ""type"": ""Button"",
                    ""id"": ""9e5df46c-c460-4bb3-a389-4a09090d96e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepEnter"",
                    ""type"": ""Button"",
                    ""id"": ""40de9811-355d-45af-bf9b-9b54699e3b67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepRightButton"",
                    ""type"": ""Button"",
                    ""id"": ""0ba54850-714a-44f9-9c6a-987f08922f32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExepLeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""ae720a5f-f9cc-40c2-9a9e-ef355fc9ad66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""17e47129-913b-4559-a70e-21be6743a4a8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3603f9f-2952-4364-a986-fe22419b1751"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MeleeAtk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e18e89b-2169-4d68-88d0-a5cc53c215ff"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""495e37a5-8157-4ba7-8905-32d80662bb4b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02cb19bc-d464-46dd-af88-c8665bed4ced"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84a94999-fdab-495a-a6e9-579bba57dc47"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6e8ec37-bf5c-428f-a10e-43e7ac854e83"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33ba4688-c093-4493-a3d6-62d75c074cf0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53d28d9a-cc4c-4642-84e6-5fbcb1b638fc"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StarFruit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64dd67a7-8401-49fe-aae0-666a0d34c1cf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a54a69a6-6cd9-4be0-a7db-7210ad2b0b67"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c509cb8-16db-4a66-9f04-4be390d34ebb"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edd6f020-7f90-4f38-9af5-a247d2ce4227"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19db260b-7fa2-4ede-a253-158dab45b187"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56919db3-ae3b-456e-9df7-6b12ce5052ad"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5effd75-de40-4cea-957c-d3e537d9a9a8"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""e8dc1de7-7361-45b7-8d00-b42906ac91df"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""111c1266-02c5-4518-9b97-ef8159a2f1d9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4a1a65f4-3ee0-4ab3-955e-6729c8d20c0e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35e67696-46aa-4520-b02c-9c351aee312e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b0fe0b71-b607-46f3-b8ee-d66794543f56"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""046950b0-dd3b-422e-86da-6b45f6ab1f40"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""0f4026df-f8db-4bac-893a-5a50ea6d14c6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0acbacbf-3706-4df2-92c9-0d8b4bf67ae1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e541fe7-a74b-409c-8d38-205977967f46"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepEsc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e39530c-ad82-4044-a5bb-003f25209868"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5ecf0f6-562f-41de-a68b-005852ba4f2c"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepLeftShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""514656cd-825f-461f-aa71-466698f3587a"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepLeftAlt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80cc0306-890b-413e-a5d2-c1dd0e99c989"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepEnter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a4b9b27-ee43-479c-98a6-d9f13b501ca4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepRightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91ebcbb1-04e6-41ee-bf8e-9e7a3123d563"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExepLeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerExeptions"",
            ""id"": ""56776dff-4727-4d8a-bd3a-f3267f1eaf7d"",
            ""actions"": [
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""38278a65-6810-493e-bb56-44fcb69877ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""0aef304c-b63c-4159-8b84-6b7b0da05a40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftShift"",
                    ""type"": ""Button"",
                    ""id"": ""5acc88a3-5802-4709-a978-b88eeb351596"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAlt"",
                    ""type"": ""Button"",
                    ""id"": ""4d674a8d-ae59-4fc5-9955-b7f10fb52e41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""d665d2c1-ef92-47fd-9b2d-a70e892e55aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightButton"",
                    ""type"": ""Button"",
                    ""id"": ""b44acab0-f5a5-4443-b776-0ca2e1319a3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""f24d7294-3ca7-4c38-a5b6-cfa5a6f476c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8890b8a-ca01-472a-baa0-c1217fd6f7c9"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d11b9613-deb0-4686-a9f8-bf83bc635d77"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88eedc9a-5ae0-40f6-adbb-006351c36c60"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAlt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a1e507c-7613-4fe8-a78a-089959e7d5f5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c592db1-8dd3-4f0e-9d3a-e5988d9676fa"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81f08abf-259f-4c34-8597-bd758ce1a087"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b936435d-1950-433c-ad5f-d28e0c0b3c6d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Move = m_PlayerInput.FindAction("Move", throwIfNotFound: true);
        m_PlayerInput_MousePosition = m_PlayerInput.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerInput_MeleeAtk = m_PlayerInput.FindAction("MeleeAtk", throwIfNotFound: true);
        m_PlayerInput_Shoot = m_PlayerInput.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerInput_Reload = m_PlayerInput.FindAction("Reload", throwIfNotFound: true);
        m_PlayerInput_Dash = m_PlayerInput.FindAction("Dash", throwIfNotFound: true);
        m_PlayerInput_Pause = m_PlayerInput.FindAction("Pause", throwIfNotFound: true);
        m_PlayerInput_OpenInventary = m_PlayerInput.FindAction("OpenInventary", throwIfNotFound: true);
        m_PlayerInput_SkipDialogue = m_PlayerInput.FindAction("SkipDialogue", throwIfNotFound: true);
        m_PlayerInput_StarFruit = m_PlayerInput.FindAction("StarFruit", throwIfNotFound: true);
        m_PlayerInput_Interaction = m_PlayerInput.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerInput_Hotbar1 = m_PlayerInput.FindAction("Hotbar1", throwIfNotFound: true);
        m_PlayerInput_Hotbar2 = m_PlayerInput.FindAction("Hotbar2", throwIfNotFound: true);
        m_PlayerInput_Hotbar3 = m_PlayerInput.FindAction("Hotbar3", throwIfNotFound: true);
        m_PlayerInput_Hotbar4 = m_PlayerInput.FindAction("Hotbar4", throwIfNotFound: true);
        m_PlayerInput_Hotbar5 = m_PlayerInput.FindAction("Hotbar5", throwIfNotFound: true);
        m_PlayerInput_Hotbar6 = m_PlayerInput.FindAction("Hotbar6", throwIfNotFound: true);
        m_PlayerInput_Esc = m_PlayerInput.FindAction("Esc", throwIfNotFound: true);
        m_PlayerInput_ExepEsc = m_PlayerInput.FindAction("ExepEsc", throwIfNotFound: true);
        m_PlayerInput_ExepTab = m_PlayerInput.FindAction("ExepTab", throwIfNotFound: true);
        m_PlayerInput_ExepLeftShift = m_PlayerInput.FindAction("ExepLeftShift", throwIfNotFound: true);
        m_PlayerInput_ExepLeftAlt = m_PlayerInput.FindAction("ExepLeftAlt", throwIfNotFound: true);
        m_PlayerInput_ExepEnter = m_PlayerInput.FindAction("ExepEnter", throwIfNotFound: true);
        m_PlayerInput_ExepRightButton = m_PlayerInput.FindAction("ExepRightButton", throwIfNotFound: true);
        m_PlayerInput_ExepLeftButton = m_PlayerInput.FindAction("ExepLeftButton", throwIfNotFound: true);
        // PlayerExeptions
        m_PlayerExeptions = asset.FindActionMap("PlayerExeptions", throwIfNotFound: true);
        m_PlayerExeptions_Esc = m_PlayerExeptions.FindAction("Esc", throwIfNotFound: true);
        m_PlayerExeptions_Tab = m_PlayerExeptions.FindAction("Tab", throwIfNotFound: true);
        m_PlayerExeptions_LeftShift = m_PlayerExeptions.FindAction("LeftShift", throwIfNotFound: true);
        m_PlayerExeptions_LeftAlt = m_PlayerExeptions.FindAction("LeftAlt", throwIfNotFound: true);
        m_PlayerExeptions_Enter = m_PlayerExeptions.FindAction("Enter", throwIfNotFound: true);
        m_PlayerExeptions_RightButton = m_PlayerExeptions.FindAction("RightButton", throwIfNotFound: true);
        m_PlayerExeptions_LeftButton = m_PlayerExeptions.FindAction("LeftButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private IPlayerInputActions m_PlayerInputActionsCallbackInterface;
    private readonly InputAction m_PlayerInput_Move;
    private readonly InputAction m_PlayerInput_MousePosition;
    private readonly InputAction m_PlayerInput_MeleeAtk;
    private readonly InputAction m_PlayerInput_Shoot;
    private readonly InputAction m_PlayerInput_Reload;
    private readonly InputAction m_PlayerInput_Dash;
    private readonly InputAction m_PlayerInput_Pause;
    private readonly InputAction m_PlayerInput_OpenInventary;
    private readonly InputAction m_PlayerInput_SkipDialogue;
    private readonly InputAction m_PlayerInput_StarFruit;
    private readonly InputAction m_PlayerInput_Interaction;
    private readonly InputAction m_PlayerInput_Hotbar1;
    private readonly InputAction m_PlayerInput_Hotbar2;
    private readonly InputAction m_PlayerInput_Hotbar3;
    private readonly InputAction m_PlayerInput_Hotbar4;
    private readonly InputAction m_PlayerInput_Hotbar5;
    private readonly InputAction m_PlayerInput_Hotbar6;
    private readonly InputAction m_PlayerInput_Esc;
    private readonly InputAction m_PlayerInput_ExepEsc;
    private readonly InputAction m_PlayerInput_ExepTab;
    private readonly InputAction m_PlayerInput_ExepLeftShift;
    private readonly InputAction m_PlayerInput_ExepLeftAlt;
    private readonly InputAction m_PlayerInput_ExepEnter;
    private readonly InputAction m_PlayerInput_ExepRightButton;
    private readonly InputAction m_PlayerInput_ExepLeftButton;
    public struct PlayerInputActions
    {
        private @Default m_Wrapper;
        public PlayerInputActions(@Default wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerInput_Move;
        public InputAction @MousePosition => m_Wrapper.m_PlayerInput_MousePosition;
        public InputAction @MeleeAtk => m_Wrapper.m_PlayerInput_MeleeAtk;
        public InputAction @Shoot => m_Wrapper.m_PlayerInput_Shoot;
        public InputAction @Reload => m_Wrapper.m_PlayerInput_Reload;
        public InputAction @Dash => m_Wrapper.m_PlayerInput_Dash;
        public InputAction @Pause => m_Wrapper.m_PlayerInput_Pause;
        public InputAction @OpenInventary => m_Wrapper.m_PlayerInput_OpenInventary;
        public InputAction @SkipDialogue => m_Wrapper.m_PlayerInput_SkipDialogue;
        public InputAction @StarFruit => m_Wrapper.m_PlayerInput_StarFruit;
        public InputAction @Interaction => m_Wrapper.m_PlayerInput_Interaction;
        public InputAction @Hotbar1 => m_Wrapper.m_PlayerInput_Hotbar1;
        public InputAction @Hotbar2 => m_Wrapper.m_PlayerInput_Hotbar2;
        public InputAction @Hotbar3 => m_Wrapper.m_PlayerInput_Hotbar3;
        public InputAction @Hotbar4 => m_Wrapper.m_PlayerInput_Hotbar4;
        public InputAction @Hotbar5 => m_Wrapper.m_PlayerInput_Hotbar5;
        public InputAction @Hotbar6 => m_Wrapper.m_PlayerInput_Hotbar6;
        public InputAction @Esc => m_Wrapper.m_PlayerInput_Esc;
        public InputAction @ExepEsc => m_Wrapper.m_PlayerInput_ExepEsc;
        public InputAction @ExepTab => m_Wrapper.m_PlayerInput_ExepTab;
        public InputAction @ExepLeftShift => m_Wrapper.m_PlayerInput_ExepLeftShift;
        public InputAction @ExepLeftAlt => m_Wrapper.m_PlayerInput_ExepLeftAlt;
        public InputAction @ExepEnter => m_Wrapper.m_PlayerInput_ExepEnter;
        public InputAction @ExepRightButton => m_Wrapper.m_PlayerInput_ExepRightButton;
        public InputAction @ExepLeftButton => m_Wrapper.m_PlayerInput_ExepLeftButton;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMove;
                @MousePosition.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMousePosition;
                @MeleeAtk.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMeleeAtk;
                @MeleeAtk.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMeleeAtk;
                @MeleeAtk.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnMeleeAtk;
                @Shoot.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnShoot;
                @Reload.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnReload;
                @Dash.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnDash;
                @Pause.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnPause;
                @OpenInventary.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnOpenInventary;
                @OpenInventary.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnOpenInventary;
                @OpenInventary.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnOpenInventary;
                @SkipDialogue.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnSkipDialogue;
                @StarFruit.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnStarFruit;
                @StarFruit.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnStarFruit;
                @StarFruit.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnStarFruit;
                @Interaction.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnInteraction;
                @Hotbar1.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar1;
                @Hotbar1.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar1;
                @Hotbar1.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar1;
                @Hotbar2.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar2;
                @Hotbar2.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar2;
                @Hotbar2.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar2;
                @Hotbar3.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar3;
                @Hotbar3.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar3;
                @Hotbar3.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar3;
                @Hotbar4.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar4;
                @Hotbar4.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar4;
                @Hotbar4.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar4;
                @Hotbar5.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar5;
                @Hotbar5.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar5;
                @Hotbar5.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar5;
                @Hotbar6.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar6;
                @Hotbar6.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar6;
                @Hotbar6.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnHotbar6;
                @Esc.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnEsc;
                @ExepEsc.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEsc;
                @ExepEsc.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEsc;
                @ExepEsc.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEsc;
                @ExepTab.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepTab;
                @ExepTab.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepTab;
                @ExepTab.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepTab;
                @ExepLeftShift.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftShift;
                @ExepLeftShift.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftShift;
                @ExepLeftShift.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftShift;
                @ExepLeftAlt.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftAlt;
                @ExepLeftAlt.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftAlt;
                @ExepLeftAlt.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftAlt;
                @ExepEnter.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEnter;
                @ExepEnter.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEnter;
                @ExepEnter.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepEnter;
                @ExepRightButton.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepRightButton;
                @ExepRightButton.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepRightButton;
                @ExepRightButton.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepRightButton;
                @ExepLeftButton.started -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftButton;
                @ExepLeftButton.performed -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftButton;
                @ExepLeftButton.canceled -= m_Wrapper.m_PlayerInputActionsCallbackInterface.OnExepLeftButton;
            }
            m_Wrapper.m_PlayerInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @MeleeAtk.started += instance.OnMeleeAtk;
                @MeleeAtk.performed += instance.OnMeleeAtk;
                @MeleeAtk.canceled += instance.OnMeleeAtk;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @OpenInventary.started += instance.OnOpenInventary;
                @OpenInventary.performed += instance.OnOpenInventary;
                @OpenInventary.canceled += instance.OnOpenInventary;
                @SkipDialogue.started += instance.OnSkipDialogue;
                @SkipDialogue.performed += instance.OnSkipDialogue;
                @SkipDialogue.canceled += instance.OnSkipDialogue;
                @StarFruit.started += instance.OnStarFruit;
                @StarFruit.performed += instance.OnStarFruit;
                @StarFruit.canceled += instance.OnStarFruit;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
                @Hotbar1.started += instance.OnHotbar1;
                @Hotbar1.performed += instance.OnHotbar1;
                @Hotbar1.canceled += instance.OnHotbar1;
                @Hotbar2.started += instance.OnHotbar2;
                @Hotbar2.performed += instance.OnHotbar2;
                @Hotbar2.canceled += instance.OnHotbar2;
                @Hotbar3.started += instance.OnHotbar3;
                @Hotbar3.performed += instance.OnHotbar3;
                @Hotbar3.canceled += instance.OnHotbar3;
                @Hotbar4.started += instance.OnHotbar4;
                @Hotbar4.performed += instance.OnHotbar4;
                @Hotbar4.canceled += instance.OnHotbar4;
                @Hotbar5.started += instance.OnHotbar5;
                @Hotbar5.performed += instance.OnHotbar5;
                @Hotbar5.canceled += instance.OnHotbar5;
                @Hotbar6.started += instance.OnHotbar6;
                @Hotbar6.performed += instance.OnHotbar6;
                @Hotbar6.canceled += instance.OnHotbar6;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @ExepEsc.started += instance.OnExepEsc;
                @ExepEsc.performed += instance.OnExepEsc;
                @ExepEsc.canceled += instance.OnExepEsc;
                @ExepTab.started += instance.OnExepTab;
                @ExepTab.performed += instance.OnExepTab;
                @ExepTab.canceled += instance.OnExepTab;
                @ExepLeftShift.started += instance.OnExepLeftShift;
                @ExepLeftShift.performed += instance.OnExepLeftShift;
                @ExepLeftShift.canceled += instance.OnExepLeftShift;
                @ExepLeftAlt.started += instance.OnExepLeftAlt;
                @ExepLeftAlt.performed += instance.OnExepLeftAlt;
                @ExepLeftAlt.canceled += instance.OnExepLeftAlt;
                @ExepEnter.started += instance.OnExepEnter;
                @ExepEnter.performed += instance.OnExepEnter;
                @ExepEnter.canceled += instance.OnExepEnter;
                @ExepRightButton.started += instance.OnExepRightButton;
                @ExepRightButton.performed += instance.OnExepRightButton;
                @ExepRightButton.canceled += instance.OnExepRightButton;
                @ExepLeftButton.started += instance.OnExepLeftButton;
                @ExepLeftButton.performed += instance.OnExepLeftButton;
                @ExepLeftButton.canceled += instance.OnExepLeftButton;
            }
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);

    // PlayerExeptions
    private readonly InputActionMap m_PlayerExeptions;
    private IPlayerExeptionsActions m_PlayerExeptionsActionsCallbackInterface;
    private readonly InputAction m_PlayerExeptions_Esc;
    private readonly InputAction m_PlayerExeptions_Tab;
    private readonly InputAction m_PlayerExeptions_LeftShift;
    private readonly InputAction m_PlayerExeptions_LeftAlt;
    private readonly InputAction m_PlayerExeptions_Enter;
    private readonly InputAction m_PlayerExeptions_RightButton;
    private readonly InputAction m_PlayerExeptions_LeftButton;
    public struct PlayerExeptionsActions
    {
        private @Default m_Wrapper;
        public PlayerExeptionsActions(@Default wrapper) { m_Wrapper = wrapper; }
        public InputAction @Esc => m_Wrapper.m_PlayerExeptions_Esc;
        public InputAction @Tab => m_Wrapper.m_PlayerExeptions_Tab;
        public InputAction @LeftShift => m_Wrapper.m_PlayerExeptions_LeftShift;
        public InputAction @LeftAlt => m_Wrapper.m_PlayerExeptions_LeftAlt;
        public InputAction @Enter => m_Wrapper.m_PlayerExeptions_Enter;
        public InputAction @RightButton => m_Wrapper.m_PlayerExeptions_RightButton;
        public InputAction @LeftButton => m_Wrapper.m_PlayerExeptions_LeftButton;
        public InputActionMap Get() { return m_Wrapper.m_PlayerExeptions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerExeptionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerExeptionsActions instance)
        {
            if (m_Wrapper.m_PlayerExeptionsActionsCallbackInterface != null)
            {
                @Esc.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEsc;
                @Tab.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnTab;
                @Tab.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnTab;
                @Tab.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnTab;
                @LeftShift.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftShift;
                @LeftShift.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftShift;
                @LeftShift.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftShift;
                @LeftAlt.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftAlt;
                @LeftAlt.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftAlt;
                @LeftAlt.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftAlt;
                @Enter.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnEnter;
                @RightButton.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnRightButton;
                @RightButton.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnRightButton;
                @RightButton.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnRightButton;
                @LeftButton.started -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftButton;
                @LeftButton.performed -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftButton;
                @LeftButton.canceled -= m_Wrapper.m_PlayerExeptionsActionsCallbackInterface.OnLeftButton;
            }
            m_Wrapper.m_PlayerExeptionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @Tab.started += instance.OnTab;
                @Tab.performed += instance.OnTab;
                @Tab.canceled += instance.OnTab;
                @LeftShift.started += instance.OnLeftShift;
                @LeftShift.performed += instance.OnLeftShift;
                @LeftShift.canceled += instance.OnLeftShift;
                @LeftAlt.started += instance.OnLeftAlt;
                @LeftAlt.performed += instance.OnLeftAlt;
                @LeftAlt.canceled += instance.OnLeftAlt;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @RightButton.started += instance.OnRightButton;
                @RightButton.performed += instance.OnRightButton;
                @RightButton.canceled += instance.OnRightButton;
                @LeftButton.started += instance.OnLeftButton;
                @LeftButton.performed += instance.OnLeftButton;
                @LeftButton.canceled += instance.OnLeftButton;
            }
        }
    }
    public PlayerExeptionsActions @PlayerExeptions => new PlayerExeptionsActions(this);
    public interface IPlayerInputActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMeleeAtk(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnOpenInventary(InputAction.CallbackContext context);
        void OnSkipDialogue(InputAction.CallbackContext context);
        void OnStarFruit(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnHotbar1(InputAction.CallbackContext context);
        void OnHotbar2(InputAction.CallbackContext context);
        void OnHotbar3(InputAction.CallbackContext context);
        void OnHotbar4(InputAction.CallbackContext context);
        void OnHotbar5(InputAction.CallbackContext context);
        void OnHotbar6(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnExepEsc(InputAction.CallbackContext context);
        void OnExepTab(InputAction.CallbackContext context);
        void OnExepLeftShift(InputAction.CallbackContext context);
        void OnExepLeftAlt(InputAction.CallbackContext context);
        void OnExepEnter(InputAction.CallbackContext context);
        void OnExepRightButton(InputAction.CallbackContext context);
        void OnExepLeftButton(InputAction.CallbackContext context);
    }
    public interface IPlayerExeptionsActions
    {
        void OnEsc(InputAction.CallbackContext context);
        void OnTab(InputAction.CallbackContext context);
        void OnLeftShift(InputAction.CallbackContext context);
        void OnLeftAlt(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnRightButton(InputAction.CallbackContext context);
        void OnLeftButton(InputAction.CallbackContext context);
    }
}
